spring.datasource.url: jdbc:mysql://localhost:3306/springbootapp?useSSL=false&serverTimezone=UTC
spring.datasource.username: root
spring.datasource.password: rootroot
spring.jpa.hibernate.ddl-auto: update
spring.jpa.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect