spring.datasource.url: jdbc:${CLEARDB_DATABASE_URL:mysql://localhost:3306/springbootapp?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}

spring.jpa.hibernate.ddl-auto: none
spring.jpa.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

spring.flyway.baselineOnMigrate : true
spring.flyway.validateOnMigrate : false
spring.jpa.show-sql: false

spring.servlet.multipart.max-file-size: -1
spring.servlet.multipart.max-request-size: -1
server.port: ${PORT:8080}
